### ISSUE TITLE
wpdl isn't working for a site that wp-json-scraper successfully scrapes

### ISSUE THREAD

**Issue by God-damnit-all** [jtiala/wpdl#20]
I was interested in seeing how this tool compares to [wp-json-scraper](https://github.com/MickaelWalter/wp-json-scraper), but while it worked for one of the sites I've used wp-json-scraper on, it didn't work on another.

The site it's not working on is https://powershellisfun.com/

---

_Sidenote: In your README.md you can remove the bit about `npm run scrape -- ` since npx is bundled with npm nowadays._

**Comment by jtiala** [comment]
Hi!
For me it seems to be working correctly. I tried to scrape one of each supported data type with the following command:
```sh
npx wpdl --url https://powershellisfun.com --pages --posts --comments --media --tags --categories --users --limitItems 1
```

If it's still not working for you, could you please give me steps to reproduce the error and I can try to help you out!


The `npm run scrape` instruction is for running the script locally, not from npm. For example if someone wants to tinker with the code before runnig it. But I agree, `npx` nicer for local scripts too: `npx . --url ...`. I'll update the docs, thanks!

**Comment by jtiala** [comment]
Closed as stale.
